version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-cache

      - run: apt-get update && apt-get -y install pkg-config zip g++ zlib1g-dev unzip python curl ocl-icd-opencl-dev opencl-headers
      - run: cd /tmp/ && curl -LO https://github.com/bazelbuild/bazel/releases/download/3.7.1/bazel-3.7.1-installer-linux-x86_64.sh
      - run: bash /tmp/bazel-3.7.1-installer-linux-x86_64.sh
      - run: cd test && cp .bazelrc.ci .bazelrc
      - run: cd test && /usr/local/bin/bazel test --test_output=errors //...
